pull_request_rules:
  - name: Automatic merge
    conditions:
      - or:
          - 'author=dependabot[bot]'
          - 'author=more-bump[bot]'
      - -draft
      - -merged
      - -closed
      - check-success=build
      - check-success=test
      - check-success=codecov/patch
      - check-success=codecov/project
    actions:
      queue:
        method: squash
        name: default

queue_rules:
  - name: default
    conditions:
      - check-success=build
      - check-success=test
      - check-success=codecov/patch
      - check-success=codecov/project
