
pull_request_rules:
  - name: Handle merged
    conditions:
      - 'label=wait-merge'
      - or:
          - merged
          - closed
    actions:
      label:
        remove: ["wait-merge"]
  - name: Automatic merge
    conditions: []
    actions:
      queue:
queue_rules:
  - name: default
    queue_conditions:
      - or:
          - 'author=dependabot[bot]'
          - 'author=more-bump[bot]'
          - 'label=wait-merge'
      - -draft
      - -merged
      - -closed
      - check-success=build
      - check-success=test
      - check-success=codecov/patch
      - check-success=codecov/project
    merge_conditions:
      - check-success=build
      - check-success=test
      - check-success=codecov/patch
      - check-success=codecov/project
    merge_method: squash
