version: "2"
linters:
  enable:
    - goheader
  settings:
    goheader:
      values:
        regexp:
          year: '[0-9]{4}'
      template: |-
        Copyright {{ year }} The Funeypot Authors. All rights reserved.
        SPDX-License-Identifier: MIT
