version: 1

builds:
  # Make sure the os and arch are supported by modernc.org/sqlite.
  # see https://pkg.go.dev/modernc.org/sqlite#hdr-Supported_platforms_and_architectures
  - id: "common"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64
  - id: "linux-extra"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - "386"
      - arm
      - ppc64le
      - riscv64
      - s390x

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

changelog:
  use: github-native
