// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package inject

import (
	"context"
	"github.com/wolfogre/funeypot/internal/app/config"
	"github.com/wolfogre/funeypot/internal/app/dashboard"
	"github.com/wolfogre/funeypot/internal/app/model"
	"github.com/wolfogre/funeypot/internal/app/server"
)

// Injectors from wire.go:

func NewEntrypoint(ctx context.Context, configFile string) (*Entrypoint, error) {
	configConfig, err := config.Load(configFile)
	if err != nil {
		return nil, err
	}
	ssh := configConfig.Ssh
	database := configConfig.Database
	modelDatabase, err := model.NewDatabase(database)
	if err != nil {
		return nil, err
	}
	abuseipdb := configConfig.Abuseipdb
	client := newAbuseipdbClient(abuseipdb)
	handler := server.NewHandler(ctx, modelDatabase, client)
	sshServer, err := server.NewSshServer(ssh, handler)
	if err != nil {
		return nil, err
	}
	http := configConfig.Http
	configDashboard := configConfig.Dashboard
	dashboardServer, err := dashboard.NewServer(configDashboard, modelDatabase)
	if err != nil {
		return nil, err
	}
	httpServer := server.NewHttpServer(http, handler, dashboardServer)
	ftp := configConfig.Ftp
	ftpServer := server.NewFtpServer(ftp, handler)
	entrypoint := newEntrypoint(sshServer, httpServer, ftpServer)
	return entrypoint, nil
}
