// Code generated by "stringer -type BruteAttemptKind -linecomment -output attempt_kind.go"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BruteAttemptKindSsh-1]
	_ = x[BruteAttemptKindHttp-2]
}

const _BruteAttemptKind_name = "sshhttp"

var _BruteAttemptKind_index = [...]uint8{0, 3, 7}

func (i BruteAttemptKind) String() string {
	i -= 1
	if i < 0 || i >= BruteAttemptKind(len(_BruteAttemptKind_index)-1) {
		return "BruteAttemptKind(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _BruteAttemptKind_name[_BruteAttemptKind_index[i]:_BruteAttemptKind_index[i+1]]
}
